interface OptionalDepartment {
  budgetFrom?: number;
  budgetTo?: number;
}

export interface Department extends OptionalDepartment {
  departmentCode: string;
  departmentName: string;
  status: string;
  province: string;
  budget: number;
  telephone: string;
  remark: string;
}

export interface DepartmentCondition extends OptionalDepartment {
  departmentCode?: string;
  departmentName?: string;
  status?: string;
  province?: string;
  budget?: number;
  telephone?: string;
  remark?: string;
}

// Generated by https://quicktype.io

export interface Characters {
  url: string;
  name: string;
  gender: string;
  culture: string;
  born: string;
  died: string;
  titles: string[];
  aliases: string[];
  father: string;
  mother: string;
  spouse: string;
  allegiances: any[];
  books: string[];
  povBooks: any[];
  tvSeries: string[];
  playedBy: string[];
}
